---
- name: Launching Workflow
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    ansible_tower_ip: summitrhel74-summitcloudformswo-jeuhusbi.srv.ravcloud.com
    ## this variable needs to be set to the corresponding workflow template in tower
    workflow_job_template_id: "{{ workflow_id }}"
    # tower_user & tower_pass are provided in the encrypted vars below

  roles:
  - 1.0L-wf_launcher
