---
- name: Building Initial Demo Page
  hosts: all
  gather_facts: False
  connection: local

  vars:
    ansible_tower_ip: # this is set in Tower Inventory
    team: # provided by provisioner
    student: # provided by provisioner
    app01_ip: # this will be conditionally set in the role
    app02_ip: # this will be conditionally set in the role
    elb_ip: # this will be retreived from host_)vars

  roles:
  - web_demo_page_builder
