---
- name: Attach instances to AWS ELB
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    student: student01
    elb_name: "{{ student }}-elb"

  tasks:
    - name: create alarm
      ec2_metric_alarm:
        state: present
        region: us-west-1
        name: "HealthyHostCount"
        metric: "HealthyHostCount"
        namespace: "AWS/ELB"
        statistic: Sum
        comparison: "<"
        threshold: 2
        period: 60
        evaluation_periods: 1
        unit: "Count"
        description: "This will alarm when the count of healthy hosts is less than 2 "
        dimensions: {'LoadBalancerName':'{{ elb_name }}'}
        alarm_actions: ["arn:aws:sns:us-west-1:662766996214:AWSConfig_topic"]
