---
# This playbook deploys a simple website.
- name: Install apache httpd and deploy website
  hosts: all
  gather_facts: true
  become: true

  vars:
    webarchive: energy_corpsite.zip

  roles:
    - 1.0p2-install_apache_httpd
