---
- name: Create new EC2 instances
  hosts: all
  gather_facts: false
  connection: local

  vars:
    region:   us-west-1
    ami: ami-01b0e074974547d44
    keypair:  summit-root
    set_dns:  False
    vpc_subnet: subnet-23ec8c78
    tags:
      name: "{{ instance_name }}"
      env:  "{{ tags_env  | default('prod') }}"
      type: "{{ tags_type | default('app') }}"
    wait_for_ssh: False

  tasks:
    - name: Launch instance
      ec2:
        keypair: "{{ keypair }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        group: Web Servers
        count: 1
        vpc_subnet_id: "{{ vpc_subnet }}"
        region: "{{ region }}"
        assign_public_ip: yes
        instance_tags: "{{ tags }}"
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: associate an elastic IP with an instance
      ec2_eip:
        device_id: "{{ item }}"
        region: "{{ region }}"
      with_items: "{{ ec2.instance_ids }}"

    - name: Instance info
      debug:
        msg: "{{ item.id }} {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
