---
# This playbook deploys a simple website.
- name: Install apache httpd and deploy website
  hosts: all
  become: true

  vars:
    http_port: 80
    https_port: 443

  roles:
    - 1.0p2-install_apache_httpd
