---
- name: Launching Workflow
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    ansible_tower_ip: summitrhel74-summitcloudformswo-jeuhusbi.srv.ravcloud.com
    ## NORMALLY, this variable needs to be set to the corresponding workflow template in tower
    ## However in this playbook I'm setting the corresponding workflow id based on the supplied student id
    ## I do this lookup in the wf_laucher_vars.yml
    #
    # workflow_job_template_id: "{{ workflow_id }}"
    #
    ###
    ## the tower credentials below are set in encrypted_wf_laucher_vars.yml
    ###
    #
    # tower_user
    # tower_pass

  roles:
  - 2.0L-webapp_fixer_wf_launcher
