---
- name: Create new EC2 instances
  hosts: localhost
  gather_facts: true
  connection: local

  vars:
    region: us-west-1
    ami: ami-01b0e074974547d44
    keypair: summit-root
    vpc_subnet: subnet-23ec8c78

  tasks:
    - name: Provision EC2 instance
      ec2:
        keypair: "{{ keypair }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        group: Web Servers
        count: 1
        vpc_subnet_id: "{{ vpc_subnet }}"
        region: "{{ region }}"
        assign_public_ip: yes
        instance_tags:
          Name: "{{ student }}-app03"
          owner: "{{ student }}"
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
