---
- name: Delete ALL EC2 instances and componanets
  hosts: all
  gather_facts: false
  connection: local

  vars:
    region: us-west-1
    ami: ami-01b0e074974547d44
    keypair: summit-root
    vpc_subnet: subnet-23ec8c78

  tasks:
    - name: Removing EC2 instance
      ec2:
        instance_id: "{{ ec2_id }}"
        wait: yes
        group: Web Servers
        vpc_subnet_id: "{{ vpc_subnet }}"
        region: "{{ region }}"
        state: absent

    - name: Removing load balancer
      ec2_elb_lb:
        name: "{{ item }}"
        region: us-west-1
        state: absent
      with_sequence: start=1 end=10 format=student%02x-elb
