---
- name: Delete ALL EC2 instances and componanets
  hosts: all
  gather_facts: false
  connection: local

  vars:
    region: us-west-1
    ami: ami-01b0e074974547d44
    keypair: summit-root
    vpc_subnet: subnet-23ec8c78

  tasks:
    - name: Removing EC2 instance
      ec2:
        wait: yes
        group: Web Servers
        vpc_subnet_id: "{{ vpc_subnet }}"
        region: "{{ region }}"
        state: absent

      - name: Removing load balancer
        ec2_elb_lb:
          name: "{{ item }}"
          state: absent
        with_items:
          - student01-elb
          - student02-elb
          - student03-elb
          - student04-elb
          - student05-elb
          - student06-elb
          - student07-elb
          - student08-elb
          - student09-elb
          - student10-elb
