---
- name: Create new EC2 instances
  hosts: all
  gather_facts: false
  connection: local

  vars:
    region: us-west-1
    ami: ami-01b0e074974547d44
    keypair: summit-root
    vpc_subnet: subnet-23ec8c78

  tasks:
    - name: Provision EC2 instance
      ec2:
        wait: yes
        group: Web Servers
        count: 1
        vpc_subnet_id: "{{ vpc_subnet }}"
        region: "{{ region }}"
        state: absent
