---
- name: Create Active Directory Users
  hosts: all
  gather_facts: false
  connection: local

  vars:

  tasks:
    - name: Creating Users
      win_domain_user:
        name: "{{ item }}"
        password: "{{ password }}"
        state: present
        path: ou=test,dc=domain,dc=local
        groups:
          - Domain Admins
      with_sequence: start=0 end=60 format=student%02x-elb
