---
- name: "Setting variables"
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Creating Users
  win_domain_user:
  #  name: "{{ item }}"
    name: student01
    password: "{{ password }}"
    state: present
    path: ou=myad,dc=rhlabs,dc=net
    groups:
      - Domain Admins
  #with_sequence: start=0 end=60 format=student%02xb
