---
- name: Undeploy HelloWorld to JBoss
  jboss:
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    deployment: helloworld.war
    state: absent

- name: Undeploy Ticket Monster to JBoss
  jboss:
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    deployment: ticket-monster.war
    state: absent