---
- name: Launch instance
  ec2:
    keypair: "{{ keypair }}"
    instance_type: t2.micro
    image: "{{ ami }}"
    wait: yes
    group: Web Servers
    count: 1
    vpc_subnet_id: "{{ vpc_subnet }}"
    region: "{{ region }}"
    assign_public_ip: yes
    instance_tags: "{{ tags }}"
  loop: 
    - "{{ student }}-app01"
    - "{{ student }}-app02"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

- name: associate an elastic IP with an instance
  ec2_eip:
    device_id: "{{ item }}"
    region: "{{ region }}"
  with_items: "{{ ec2.instance_ids }}"

- name: Instance info
  debug:
    msg: "{{ item.id }} {{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"
