## the sections below that are commented out are an attempt to do dynamic credential switching
## But for some reason the module is barfing so I need to investigate why that is because
## this should work, possible bug

- name: "Gather Playbook Variables"
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Provision EC2 instance
  ec2:
    aws_access_key: "{{ creds[team].aws_user }}"
    aws_secret_key: "{{ creds[team].aws_pass }}"
    keypair: "{{ keypair }}"
    instance_type: t2.micro
    image: "{{ creds[team].aws_ami }}"
    wait: yes
    group: Web Servers
    count: 1
    vpc_subnet_id: "{{ creds[team].vpc_subnet }}"
    region: "{{ region }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ item }}""
      owner: "{{ student }}"
      team: "{{ team }}"
  register: ec2
  with_items:
    - {{ student }}-app01
    - {{ student }}-app02

- debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
      with_items: "{{ec2.results}}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
