---

- name: Provision application load balancer
  ec2_elb_lb:
    name: "{{ student }}-elb"
    state: present
    region: us-west-1
    validate_certs: no
    subnets:
      - subnet-23ec8c78
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
        instance_port: 80
