---
- name: "Gathering required variables"
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Provisioning application load balancer
  ec2_elb_lb:
    name: "{{ elb_name }}"
    state: present
    region: us-west-1
    validate_certs: no
    # subnets:
    #   - subnet-23ec8c78
    zones:
       - "{{ towers[team].zone_1 }}"
       - "{{ towers[team].zone_2 }}"
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
        instance_port: 80
  register: ec2_elb

- name: Dumping ELB IP
  elb_classic_lb_facts:
    names: "{{ elb_name }}"
    region: us-west-1
  register: elb_facts

- debug:
    msg: "{{ elb_facts.elbs.0.dns_name }}"
